#-------------------------------
# General Site Settings
baseURL = "/"
languageCode = "en-us"
title = "The Whiterocker"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 6


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "SERVICES"
    url = "/services/"
    weight = 2

  [[menu.main]]
    name = "SCHEDULE"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "COMPANY"
    weight = 5
    hasChildren = true

      [[menu.main]]
        parent = "COMPANY"
        name = "ABOUT THE CLUB"
        url = "/about/"
        weight = 1

      [[menu.main]]
        parent = "COMPANY"
        name = "JOIN THE TEAM"
        url = "/career-opportunities/"
        weight = 2

      [[menu.main]]
        parent = "COMPANY"
        name = "CONTACT US"
        url = "/contact/"
        weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "HOME"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "SERVICES"
    url = "/projects/"
    weight = 2

  [[menu.footer]]
    name = "ABOUT"
    url = "/about/"
    weight = 4


  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "www.thewhiterockerpoker.com"
    cta_button_text = "MEMBER LOGIN"


[params]
  logo = "/images/whiterocker-logo-light.png"
  logo_dark = "/images/whiterocker-logo-dark.png"
  description = "Gerous is a modern portfolio Hugo theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Author Settings
  [params.author]
    author_name = ""
    author_avatar = ""


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero_title = ""
    hero_description = "Explore "

  [params.hero_logos]
    enable = true

  [[params.hero_logo_image]]
    image_alt = "Apple Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Adobe Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "HP Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Netlify Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Dropbox Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "EA Logo"
    image_url = "https://via.placeholder.com/80x80"

  [[params.hero_logo_image]]
    image_alt = "Chrome Logo"
    image_url = "https://via.placeholder.com/80x80"


  #-------------------------------
  # Slider Featured Settings
  [params.featured]
    enable = false
    featured_title = "Selected Work"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = false
    projects_title= "Recent Work"
    projects_description= ""


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonials_intro = "Don't take my word for it"
    testimonials_title = "See what our happy clients say..."
    testimonials_info = "Join over <b>10K+</b> Prefessionals"

  [[params.testimonial_item]]
    name = "Martin Vetrovs"
    image = "https://via.placeholder.com/120x120"
    designation = "Data Scientist"
    title = "Incredible attention to detail"
    content = "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  [[params.testimonial_item]]
    name = "Hanna Herwitz"
    image = "https://via.placeholder.com/120x120"
    designation = "UI/UX Designer"
    title = "Collaborative partnership"
    content = "Our partnership with this team was characterized by open communication and collaborative efforts. They took the time to understand our goals and delivered a solution that perfectly aligns with our business objectives. Looking forward to future collaborations."

  #-------------------------------
  # Locations Section
  [params.locations]
    enable = true
    locations_intro = "Areas of Operation"
    locations_title = "We're happy to see you all around the..."
    locations_info = "Proudly serving the Dallas/Ft. Worth Metroplex and beyond."

  [[params.location_item]]
    name = "City of Dallas"
    image = "/images/locations/dallas.jpg"
    designation = ""
    title = "City of Dallas"
    content = ""

    [[params.location_item]]
    name = "City of Irving"
    image = "/images/locations/irving.jpg"
    designation = ""
    title = "City of Irving"
    content = ""

    [[params.location_item]]
    name = "City of Garland"
    image = "/images/locations/garland.png"
    designation = ""
    title = "City of Garland"
    content = ""

    [[params.location_item]]
    name = "City of Forth Worth"
    image = "/images/locations/ftworth.png"
    designation = ""
    title = "City of Fort Worth"
    content = ""

  #-------------------------------
  # Faq (Frequently asked questions) Settings
  [params.faq]
    enable = true
    faq_intro = "Need some answers?"
    faq_title = "Frequently Asked Questions"

  [[params.faq_item]]
    title = "Where can I find The Whiterocker on weekends?"
    description = "The Whiterocker is available to the public most weekends, often stationed at sporting events and popular public spaces around Dallas. Check our schedule to find out where we’ll be next!"

  [[params.faq_item]]
    title = "Can I rent The Whiterocker food truck for private events?"
    description = "Yes! The Whiterocker is available for private catering, offering our full cafe service, food menu, and an optional poker dealer for an interactive experience. Bookings can be customized for parties, gatherings, and special events."

  [[params.faq_item]]
    title = "What services are included in a private catering rental?"
    description = "Private rentals include our food and cafe services, with the option to add a poker dealer to host a game either inside the truck or in a setup near the truck, based on your preference."

  [[params.faq_item]]
    title = "Is there a minimum or maximum rental time for private events?"
    description = "We work to accommodate your event’s unique needs. Our team will help customize timing and details, whether it's a few hours or a full day. Contact us for more specifics on scheduling."

  [[params.faq_item]]
    title = "How far in advance should I book The Whiterocker for a private event?"
    description = "We recommend booking as early as possible, especially for weekend events, as availability can fill up quickly. Reach out to us with your event date, and we’ll work to accommodate your schedule."

  #-------------------------------
  # Faq (Frequently asked questions) Settings
  [params.membershipsfaq]
    enable = true
    faq_intro = "Need some answers?"
    faq_title = "Frequently asked membership questions"

  [[params.membershipsfaq_item]]
    title = "How much is a membership?"
    description = "Memberships start at $200 a month."

  [[params.membershipsfaq_item]]
    title = "So only club members are able to use the game table?"
    description = "Correct. The game table is inside the clubhouse and one must be a member in order to have access."


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog_intro = "What’s new?"
    blog_title = "Latest from blog"


  #-------------------------------
  # Author Section Settings
  [params.author_section]
    enable = true
    author_section_title = "Welcome to The Whiterocker"
    author_section_subtitle = ""
    author_section_description = "The Whiterocker is a food truck experience like no other. Inspired by the serenity and camaraderie found around White Rock Lake, we’ve crafted a mobile cafe that’s all about bringing people together over great food and drinks. Whether you’re stopping by for a fresh brew, a tasty bite, or just to relax and connect, The Whiterocker is here to serve up comfort and community wherever you find us. Join us as we roll through the city, spreading good vibes and creating memorable moments, one stop at a time."
    author_section_image = ""
    author_section_image_alt = ""
    author_section_button_text = ""
    author_section_button_link = "/contact"


  #-------------------------------
  # Footer Settings

  # Social Links
  [[params.social]]
    icon = "fa-brands fa-facebook-f"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "fa-brands fa-tiktok"
    name = "Tiktok"
    link = "https://www.tiktok.com/"

  [[params.social]]
    icon = "fa-brands fa-instagram"
    name = "Instagram"
    link = "https://instagram.com"



  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "fa-brands fa-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://fontawesome.com/icons


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp_title = "Monthly newsletter coming soon 📬"
    mailchimp_description = "News, deals and updates. Stay up to date with everything happening around the White Rock Lake community."
    mailchimp_identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp_input_text = "Your email address"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Gerous comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false